---
title: "Graphs for HW 4"
author: "Sophia Leiker"
date: "5/22/2022"
output: html_document
---

```{r setup, include= TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(broom)
library(patchwork)
options(scipen = 999)
# reading in damages data, creating new column for squared damages
damages <- read_csv(here("data", "damages.csv")) %>% 
  mutate(warming_q = warming^2)
# reading in warming data
warming <- read_csv(here("data", "warming.csv"))
Q1 <- read_csv(here("data", "Q1.csv"))
```

```{r}
ggplot(data = Q1, aes(x = warming, y = damages_for_line_fit)) +
  geom_point(color = "black", size = 0.7) +
  geom_line(data = damages_predict, aes(x = warming, y = damages_for_line_fit), size = 1.2) +
  scale_color_gradientn(colors = c("gold", "firebrick", "darkred")) +
  theme_minimal(14) +
  labs(x = "Warming (degrees C)", y = "Damages (trillions USD)") +
  scale_x_continuous(n.breaks = 10) +
  theme(legend.position = "none")
```

```{r}
qm_damages2 <- lm(damages_for_line_fit ~ 0 + warming + warming^2, data = Q1)
damages_predict2 <- augment(qm_damages2)

ggplot(data = damages_predict2, aes(x = warming, y = damages_for_line_fit)) +
  geom_point(color = "black", size = 0.7) +
  geom_line(data = damages_predict2, aes(x = warming, y = .fitted), size = 1.2) +
  labs(x = "Warming (degrees C)", y = "Damages (USD)", title = "Damages in USD aligned with Warming in Degrees C") +
  scale_x_continuous(n.breaks = 10)
  
```


#   QUESTION 2
```{r}



```


